name: Example Workflow
on:
  pull_request:
    branches:
      - main-1
  schedule:
    - cron:  '0 0 * * *'
jobs:
  security:
    runs-on: my-github-runner
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    # Because this example is building a Gradle project, it needs to happen after setting up Java
    - name: Grant execute permission for gradlew to build my project
      run: chmod +x gradlew
    - name: Build my project with Gradle
      run: ./gradlew build
    - name: Create Black Duck Policy
      uses: blackducksoftware/create-policy-action@v0.0.1
      with:
        blackduck-url: https://ec2-34-205-17-11.compute-1.amazonaws.com
        blackduck-api-token: ZjI2MDA2MTAtY2NkMC00ZDc1LThkODctOTRkMWU2MDEzODc1OjRkYTkzMDA0LWJlNDEtNDFlMC04NGRiLTZhMDI5OGM2ZDhhZg==
        policy-name: 'My Black Duck Policy For GitHub Actions'
        no-fail-if-policy-exists: true
    - name: Run Synopsys Detect
      uses: synopsys-sig/detect-action@v0.3.0
      with:
          github-token: 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
          detect-version: 7.9.0
          blackduck-url: https://ec2-34-205-17-11.compute-1.amazonaws.com
          blackduck-api-token: ZjI2MDA2MTAtY2NkMC00ZDc1LThkODctOTRkMWU2MDEzODc1OjRkYTkzMDA0LWJlNDEtNDFlMC04NGRiLTZhMDI5OGM2ZDhhZg==
